-- STARTING AND SHUTTING DOWN  DATABSASE INSTANCES
  SQL>STARTUP
    1. NOMOUNT= STARTUP NOMOUNT
        INSTANCES STARTED 
        ONLY DBAS CAN CONNECT DATABASE IN THIS Mode
    
    2. MOUNT= STARTUP MOUNT 
        CONTROL FILES OPENED FOR THE INSTANCES
        ONLY DBAS CAN CONNECT FOR MAINTAINANCE OPERATION SUCH AS JPERFORMING FULL DATABASE RECOVERY.

    3. OPEN= STARTUP OPEN
        ALL FILES OPENED AS DESCRIBED BY CONTROL FILES FOR THE INSTANCE.
        IT IS DEFAULT AND ENEBLES NON DBA USERS TO CONNECT TO INSTANCE.